### ISSUE TITLE
Error In `portfolio_management_one.py`

### ISSUE THREAD

**Issue by vedantog** [letianzj/QuantResearch#7]
After the data is downloaded, I am getting the following error:
```
Traceback (most recent call last):
  File "portfolio_management_one.py", line 47, in <module>
    port_return = np.dot(w.T, hist_mean.as_matrix()) * 250         # annualize; 250 business days
  File "C:\Users\namit\anaconda3\lib\site-packages\pandas\core\generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```

**Comment by vedantog** [comment]
To solve this, you have to edit line `47` and change it to `port_return = np.dot(w.T, hist_mean.values()) * 250` as `df.as_matrix()` has been replaced by `df.to_numpy()`.

**Comment by letianzj** [comment]
It is deprecated since version 0.23.0. The replacement works. Thanks.
